import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigInteger;
import java.util.Properties;

public class Settings {

    static final int PORT_ID = 43594;
    static final int SUB_BUILD = 1;

    static final boolean DISABLE_USELESS_PACKETS = true;

    static String SERVER_IP = "localhost";
    static final String SERVER_NAME = "Divergent";
    static final String QUIT_URL = "";
    static final String BUILD = "Divergent 667 " + SUB_BUILD;

    static BigInteger LOGIN_RSA_MODULO = new BigInteger
            ("136914452720818738030866974552169510443780002195079066555932963918466900652770700656048535639467254948516578349788331766300501508423540632545649163609036476487799518885938398419700572373453656688641593612122959051281142073284847561395615425637341568986022676889601947424751842962049243156853076006911344463147");
    static BigInteger LOGIN_RSA_EXPONENT = new BigInteger("65537");

    private static Properties customSettings = new Properties();

    static {
        try {
            if ((new File(getCustomSettingsPath())).exists())
                customSettings.load(new FileInputStream(new File(getCustomSettingsPath())));
        } catch (IOException e) {
            e.printStackTrace();
            //ignore
        }
    }

    private static void setCustomSetting(String key, Object value) {
        customSettings.put(key, "" + value);
        saveProperties();
    }

    private static void saveProperties() {
        try {
            customSettings.store(new FileWriter(new File(getCustomSettingsPath())),
                    "Please do not edit this file by " + "hand.");
        } catch (IOException e) {
            e.printStackTrace();
            //ignore
        }
    }

    static void toggleForceLeftClick() {
        setCustomSetting("force_left_click", "" + !forceLeftClick());
    }

    static boolean forceLeftClick() {
        return (!customSettings.containsKey("force_left_click")) ? false : Boolean.valueOf((String) customSettings.get
                ("force_left_click"));
    }

    private static String getCustomSettingsPath() {
        return getCachePath() + "Settings.preferences";
    }

    static String getCachePath() {
        return System.getProperty("user.home") + "/." + SERVER_NAME + "/";
    }
}
